name: Deploy flask-api on EKS
run-name: Deploy flask-api on EKS
on: workflow_dispatch
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Configure AWS credentials POC eks
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        
      - name: Get eks config 
        run: aws eks --region eu-west-2 update-kubeconfig --name poc-eks
      
      - name: Get Namespace
        if: always()
        run: kubectl create ns flask-api
      
      - name: Deploy chart
        run: |
          cd helm
          helm install flask-api flask-api -n flask-api

